### ISSUE TITLE
IBC Command Server + Linux - "STOP" command

### ISSUE THREAD

**Issue by vakov** [IbcAlpha/IBC#30] opened 2018-11-18 17:33 UTC
In the Linux (Debian 9 + XFCE) version, I can not end IBC with the "STOP" command sent to the Command Server.
Is there a solution to the problem? Thank you

Log:
----
2018-11-18 18:13:24:847 IBC: CommandServer accepted connection from: 127.0.0.1
2018-11-18 18:13:28:656 IBC: CommandServer received command: STOP
2018-11-18 18:13:28:658 IBC: Getting main window
2018-11-18 18:13:28:658 IBC: Main window already found
2018-11-18 18:13:28:658 IBC: Scheduling backup forced exit

Telnet response:
----------------
ERROR Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@292bde6 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1afa697a[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]

**Comment by rlktradewright** [comment] 2018-11-18 18:04
Thanks for the info. I'll look into it.

**Comment by rlktradewright** [comment] 2018-11-19 22:05
Fixed in Release 3.7.3.

The problem was caused by me inadvertently including some experimental code in the previous builds.

**Comment by vakov** [comment] 2018-11-20 07:49
Thank you very much

**Closed** 2018-11-20 14:56 UTC
