### ISSUE TITLE
IBC unable to restart after 2.5 days of running. Happened multiple times.

### ISSUE THREAD

**Issue by ammar-beyond** [IbcAlpha/IBC#253] opened 2024-04-22 08:39 UTC
Hello,
My IBC start seems to crash after about 2.5 days of running. This happened multiple times with the time its crashed, almost the same every time. Please see the log file for any clues about whats going wrong.

[ibc-3.18.0_GATEWAY-1019_Wednesday.txt](https://github.com/IbcAlpha/IBC/files/15059994/ibc-3.18.0_GATEWAY-1019_Wednesday.txt)

My allocated restart time is the same in Gateway settings and IBC config file.
Can provide previous log files if required.

Thanks.

**Comment by rlktradewright** [comment] 2024-04-22 12:11
Let's collect more diagnostics.

Can you please make the following settings in `config.ini` (you'll find the relevant settings right down at the end of the file):

```
LogStructureScope=all
LogStructureWhen=activate
```

Then run it for a day or two (until the problem occurs again) and attach the logfile again.

I also have a couple of observations:

1. Why is your country set to US, but your timezone is set to `Etc/GMT+1` ? I don't think that should be a problem but I'm curious as to why you have it set to this. Yoou might find this hel;pful: https://stackoverflow.com/questions/7303580/understanding-the-etc-gmt-time-zone

2.  You don't need the auto-restart time set in both Gateway's settings and in config.ini: that just involves Gateway in unnecessary work at startup. But if you want to change it frequently, this is easier than just using the Gateway setting.

3.  You have `MinimizeMainWindow=yes` in config.ini. I have a suspicion that this might be a factor in these issues, so after you've captured the addtional diagnostics please try setting it to 'no', and see if that makes any difference.

<br>
<br>

You don't really need to read the rest of this unless you're interested.

This seems to be similar to #251. In both cases, TWS/Gateway is behaving differently from 'normal' at the IBKR nightly reset. Normally all that happens (as far as IBC is concerned) is that a dialog box is briefly displayed while TWS/Gateway re-establishes its session with the servers. IBC doesn't take any action here, it just logs the occurence of these dialogs.

So for example on 18 April we have this:

```
2024-04-18 03:24:02:397 IBC: detected frame entitled: Connecting to server...; event=Opened
2024-04-18 03:24:02:398 IBC: detected frame entitled: Connecting to server...; event=Activated
2024-04-18 03:24:02:402 IBC: detected frame entitled: Connecting to server...; event=Focused
2024-04-18 03:24:35:163 IBC: detected frame entitled: Starting application...; event=Closed
```

and everything carries on fine. That is the normal sequence.

But on 19 April we have a completely different sequence:

```
2024-04-19 03:24:07:848 IBC: detected frame entitled: Connecting to server...; event=Opened
2024-04-19 03:24:07:851 IBC: detected dialog entitled: DU6369231 Trader Workstation Configuration (Simulated Trading); event=Lost focus
2024-04-19 03:24:07:851 IBC: detected dialog entitled: DU6369231 Trader Workstation Configuration (Simulated Trading); event=Deactivated
2024-04-19 03:24:07:851 IBC: detected frame entitled: Connecting to server...; event=Activated
2024-04-19 03:24:07:857 IBC: detected frame entitled: Connecting to server...; event=Focused
2024-04-19 03:25:02:733 IBC: detected dialog entitled: Re-login is required; event=Opened
2024-04-19 03:25:02:733 IBC: Re-login to session
2024-04-19 03:25:02:733 IBC: Click button: Re-login
2024-04-19 03:25:02:811 IBC: detected frame entitled: Attempt 6: Authenticating...; event=Lost focus
2024-04-19 03:25:02:811 IBC: detected frame entitled: Attempt 6: Authenticating...; event=Deactivated
2024-04-19 03:25:02:811 IBC: detected dialog entitled: Re-login is required; event=Activated
2024-04-19 03:25:02:815 IBC: detected dialog entitled: Re-login is required; event=Focused
2024-04-19 03:25:02:816 IBC: detected dialog entitled: Re-login is required; event=Lost focus
2024-04-19 03:25:02:816 IBC: detected dialog entitled: Re-login is required; event=Deactivated
2024-04-19 03:25:02:816 IBC: detected frame entitled: Attempt 6: Authenticating...; event=Activated
2024-04-19 03:25:02:816 IBC: detected frame entitled: Attempt 6: Authenticating...; event=Focused
2024-04-19 03:25:02:816 IBC: detected dialog entitled: Re-login is required; event=Closed
2024-04-19 03:25:03:908 IBC: detected dialog entitled: Shutdown progress; event=Opened
2024-04-19 03:25:03:943 IBC: detected frame entitled: ; event=Lost focus
2024-04-19 03:25:03:943 IBC: detected frame entitled: ; event=Deactivated
2024-04-19 03:25:03:943 IBC: detected dialog entitled: Shutdown progress; event=Activated
2024-04-19 03:25:03:944 IBC: detected dialog entitled: Shutdown progress; event=Focused
2024-04-19 03:25:03:944 IBC: detected dialog entitled: Login failed; event=Opened
2024-04-19 03:25:03:944 IBC: Login failed
```

Here everything falls apart: Gateway displays the "Re-login is required" dialog, and IBC clicks the 'Re-login' button (because that's pretty much all it can do), and after that Gateway displays the 'Login failed' dialog. 

I've no idea why Gateway is behaving differently here. 

The only thing i can suggest is that we collect additional diagnostics to see if it reveals any further information about what's going on.

**Comment by ammar-beyond** [comment] 2024-04-23 11:10
Thanks for the detailed response. 
I have started IBC with the suggested log paramaters. Will update this post once a crash happens.

As per your observations; 
- The local timezone is set up so that the system starts the crontab scripts properly from 00:00 to 23:45. Not exactly sure why the country is set to US, but will look into the possibility of it being an issue if we're unable to find a solution. 
- I have removed the AutoRestart time from config.ini
- And will set the minimize window parameter no after we get an updated log.

There seems to be an additional gateway banner open after the login sequence is done. Please see screenshot.
I can't press the "Paper log in" option and when I press the "X" button, it shuts off the connected Gateway seesion.
![thumbnail_IMG_5467](https://github.com/IbcAlpha/IBC/assets/109018702/ed6b6c0b-002b-4fe2-b0ec-6c677049f18c)

**Comment by rlktradewright** [comment] 2024-04-24 11:54
The 'extra' window you see is just the Gateway login dialog. I've no idea why Gateway sometimes doesn't hide it or close it once login is completed. IBC actually tries to hide it (by setting it to non-visible) after login completes, but nothing happens. I could perhaps try to iconify it (ie minimize it in Windows-speak) but I don't like to fiddle unnecessarily with things that Gateway is in charge of. I seem to recall that this sometimes also happens when you run Gateway manually, ie without using IBC, but I rarely run Gateway at all so I might be misremembering. 

So just ignore it. You could increase the size of the main window and then it will be hidden behind it when the main window is displayed (at least, it will be if you don't minimze the main window).

I'm afraid I didn't understand your rationale for `Etc/GMT+1`.

**Comment by rlktradewright** [comment] 2024-04-25 19:21
Your mention of the 'extra' window reminded me of my attempt to hide it, which I had completely forgotten about. 

Thinking more about it, it occurred to me that this ineffective single line of code may actually be the cause of your issue and the related ones.

So I've created a new beta version of IBC: this is v3.19.0-beta.1, and you can find it here:

https://1drv.ms/f/s!AlqfLEOWDJ9Zh-klxayDSKUDSpj0Ow?e=LUbIce

I'd be grateful if you could try this version, perhaps when you've completed your diagnostic gathering.

For both Windows and Linux/macOS users, you'll need to extract the updated `IBC.jar` and `version` files to your IBC folder.

For Windows users only, you should also extract the `StartIBC.bat` file to the `scripts` subfolder in your IBC folder. And also extract the `config.ini file`, carrying forward your settings to the new version.

You may notice that there is a new ColdRestartTime setting in `config.ini`. I haven't yet decided whether to keep this feature going forward with IBC, so you can use it if you want but I may remove it (though if people find it useful I'll probably keep it). However note that this feature doesn't work properly on Linux/macOS as the scripts need some updates to support it: I'll do these if I decide to keep the feature.

**Comment by ammar-beyond** [comment] 2024-04-29 05:37
IBC still hasn't crashed as was expected. I've restarted it today so we can expect a crash sometime on Wednesday (if the previous crash behavior subsists).

Yes, I have been ignoring that extra window and I appreciate your beta release that addresses that, I will be trying it after we get the crash data.

And as for the time zone rationale, the system I have running through the crontab is designed to start scripts throughout the day. So with Etc/GMT+1 time zone selected, system time 00:00 matches with the start of the Asian futures markets. That's why I've picked that time zone, but I'm not sure why the country is set to US. This part is separate from the crashing issue but let me know if you see a better way to do things.

Thanks.

**Comment by rlktradewright** [comment] 2024-04-29 12:31
I think maybe I wasn't quite clear. My beta release has nothing to do with the 'extra' window. I've removed a line of code which was attempting to hide this window: this didn't work, but (I think) it caused the sequence of events which led to the shutdown. so by removing this line, the problem with the premature shutdown should be resolved. But the 'extra' window will still be there.

Just for clarity, there is actually nothing 'extra' about this window, it's just the normal login dialog that Gateway should hide once login has completed, but for some reason it doesn't always seem to do this. This has been a longstanding 'feature' of Gateway, but in older versions of Gateway it wasn't very noticeable because the login dialog was much smaller so it was actually behind the main Gateway window after login had completed.

Ok, I think I understand where you're coming from with the timezone now. 

But I presume your IB account is not on the IBKR Asia servers? You seem to be encountering the  European nightly reset - not in itself a problem provided your code can deal with the disconnects.

**Comment by ammar-beyond** [comment] 2024-04-30 03:48
Ahh thanks for the clarification. In that case, I'll install the update and report back if there's a crash or if there isn't after a week.

I'm located in Australia so I hope I'm on the Asian servers. Don't know how to check but either way shouldn't be a problem as the code deals fine with disconnects. 

Once again, thanks for your assistance and I'll keep this post updated after the update.

**Comment by ammar-beyond** [comment] 2024-04-30 05:25
Update: With the updated IBC.jar and version files, the Gateway login window is now gone.

**Closed** 2024-11-13 09:58 UTC
