### ISSUE TITLE
Restart fails because of "Attempted to append to non-started appender d"

### ISSUE THREAD

**Issue by acowlikeobject** [IbcAlpha/IBC#25] opened 2018-10-18 12:52 UTC
The daily auto-restart fails due to an `Attempted to append to non-started appender` error.

This seems to happen somewhat randomly.  Sometimes it'll happen on the first attempted restart, and at other times it will restart a few times successfully and fail on the 3rd or 4th restart.  (But it never goes more than a few days without hitting this error.)

These are the last few lines of the log.  Any idea what could be causing this?

```
2018-10-17 22:00:01:864 IBC: Detected dialog entitled: Shutdown progress; event=Opened
2018-10-17 22:00:01:868 IBC: Detected dialog entitled: Shutdown progress; event=Activated
2018-10-17 22:00:02:452 IBC: Detected dialog entitled: Uploading settings to server; event=Closed
2018-10-17 22:00:02:452 IBC: Detected dialog entitled: Uploading settings to server; event=Closed
2018-10-17 22:00:03:253 IBC: Detected dialog entitled: Uploading settings to server; event=Closed
2018-10-17 22:00:03,259 JTS-ShutdownTask-Shutdown_IA-8499 ERROR Attempted to append to non-started appender d
2018-10-17 22:00:03,260 NIA-Input-Queue-2 ERROR Attempted to append to non-started appender d
2018-10-17 22:00:03,265 NIA-Input-Queue-2 ERROR Attempted to append to non-started appender d
2018-10-17 22:00:03,529 NIA-Input-Queue-2 ERROR Attempted to append to non-started appender d
2018-10-17 22:00:03:621 IBC: Detected frame entitled: Loading...; event=Closed
```

**Comment by rlktradewright** [comment] 2018-10-18 13:55
Those 'Attempted to append...' lines are not the cause of anything: they are logged by TWS/Gateway when it's closing down, and are perfectly normal.

What's happening here is that TWS is simply shutting down. Since you've decided that I only need to see the very last part of the logfile, which contains nothing of any use except the fact that IBC detected the 'Shutdown progress' dialog (which is how I know that TWS is shutting down), there's not a lot more I can do to help.

So you need to find out why TWS is shutting down. If you attach the whole logfile (and I mean attach, not quote it) then I might be able to tell you something more useful.

**Comment by rlktradewright** [comment] 2018-11-14 16:41
Closed due to lack of further input.

**Closed by rlktradewright** 2018-11-14 16:41 UTC
