### ISSUE TITLE
TWS 10.15

### ISSUE THREAD

**Issue by jarsel** [IbcAlpha/IBC#165] opened 2022-04-19 05:15 UTC
Doesn't look like it's working with TWS version 10.15. Not filling username/password.

**Comment by rlktradewright** [comment] 2022-04-19 08:14
Yes I know. This was reported by issue #163, and a beta version that fixes the problem is at:

https://1drv.ms/u/s!AlqfLEOWDJ9Zh-klxayDSKUDSpj0Ow?e=hP849Z

I really must get round to releasing this properly. Only so many hours in a day...

Please leave this issue open until the new release is published, so that others are more likely to find it.

**Comment by spidLL** [comment] 2022-05-02 22:57
Thanks, that works.

**Comment by rlktradewright** [comment] 2022-07-17 22:09
Fixed in IBC 3.13.0

**Closed by rlktradewright** 2022-07-17 22:09 UTC
